### ISSUE TITLE
Move cname out of "misc" and into a new guide called "going live" or something like that.

### ISSUE THREAD

**Issue by benhalpern** [forem/forem-admin-guide#2]
The "Launching your Forem" part in the "Overview + First Steps" part makes sense, but could probably need more of an overview. Right now it's a little unclear through the docs how one might go live. I'm sure support is helping folks, but it would be a little hard to self help here. (Even though right now it involved "contact admins"...

**Comment by pkfrank** [comment]
@benhalpern it's a bit tough to reference changes made via the GitBook UI (I can't simply link a PR), but I created this page here: https://app.gitbook.com/@forem/s/forem-admin-guide/going-live

Going to close this issue for now
